
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import tung.Data;
import java.io.FileReader;
import java.io.FileWriter;
import java.lang.reflect.Array;
import java.util.Arrays;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguye
 */
public class NewJFrame extends javax.swing.JFrame {
    Data newData = new Data();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameSelfDiag1 = new javax.swing.JFrame();
        cbbcovidtested = new javax.swing.JComboBox<>();
        cbbseveresymptoms = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btntoframe3 = new javax.swing.JButton();
        cbfeverorchills = new javax.swing.JCheckBox();
        cbmild = new javax.swing.JCheckBox();
        cbnewcough = new javax.swing.JCheckBox();
        cblosstaste = new javax.swing.JCheckBox();
        cbsorethroat = new javax.swing.JCheckBox();
        cbvomiting = new javax.swing.JCheckBox();
        cbunexplained = new javax.swing.JCheckBox();
        cbnonesymp = new javax.swing.JCheckBox();
        btnbacktoOption1 = new javax.swing.JButton();
        jFrameSelfDiag2 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        cbcleanmedicalBG = new javax.swing.JCheckBox();
        btntoSelfDiag3 = new javax.swing.JButton();
        btnbackSelfDiag1 = new javax.swing.JButton();
        jFrameSelfDiag3 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnSelfDiagResult = new javax.swing.JButton();
        btnbackSelfDiag2 = new javax.swing.JButton();
        jFrameOption = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnbacktomain = new javax.swing.JButton();
        jFrameAreaStatistic = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfRegion = new javax.swing.JTextField();
        tfLocation = new javax.swing.JTextField();
        btnAreaStatisticResult = new javax.swing.JButton();
        btnbacktoOption2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        login = new javax.swing.JFrame();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        tfAge = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbbsex = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jFrameSelfDiag1.setResizable(false);
        jFrameSelfDiag1.setSize(new java.awt.Dimension(750, 600));
        jFrameSelfDiag1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrameSelfDiag1WindowClosed(evt);
            }
        });

        cbbcovidtested.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your answer.", "I was tested and their result was positive for COVID-19.", "I was tested and their result was negative for COVID 19.", "I was tested but they have not yet received their test results.", "I have not been tested in the last 10 days." }));
        cbbcovidtested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbcovidtestedActionPerformed(evt);
            }
        });

        cbbseveresymptoms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your answer.", "I am able to do normal activities like exercising.", "I can only do some daily activities like cleaning and making food.", "I can only do what's necessary such as using the bathroom or eating.", " " }));
        cbbseveresymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbseveresymptomsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("In the last 10 days, have they been tested for COVID-19 ?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Have you recently started experiencing any of these symptoms ?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("How severe are your symptoms ?");

        btntoframe3.setText("Next");
        btntoframe3.setMaximumSize(new java.awt.Dimension(91, 23));
        btntoframe3.setMinimumSize(new java.awt.Dimension(91, 23));
        btntoframe3.setPreferredSize(new java.awt.Dimension(91, 23));
        btntoframe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoframe3ActionPerformed(evt);
            }
        });

        cbfeverorchills.setText("Fever or Chills");
        cbfeverorchills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfeverorchillsActionPerformed(evt);
            }
        });

        cbmild.setText("Mild or moderate difficulty breathing");

        cbnewcough.setText("New or worsening cough");

        cblosstaste.setText("Suddently loss of taste or smell");
        cblosstaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblosstasteActionPerformed(evt);
            }
        });

        cbsorethroat.setText("Sore throat");
        cbsorethroat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsorethroatActionPerformed(evt);
            }
        });

        cbvomiting.setText("Vomiting or diarrhea");

        cbunexplained.setText("Unexplained, significant fatigue or aching throughout the body");

        cbnonesymp.setText("None of the above");

        btnbacktoOption1.setText("Previous");
        btnbacktoOption1.setMaximumSize(new java.awt.Dimension(91, 23));
        btnbacktoOption1.setMinimumSize(new java.awt.Dimension(91, 23));
        btnbacktoOption1.setPreferredSize(new java.awt.Dimension(91, 23));
        btnbacktoOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktoOption1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameSelfDiag1Layout = new javax.swing.GroupLayout(jFrameSelfDiag1.getContentPane());
        jFrameSelfDiag1.getContentPane().setLayout(jFrameSelfDiag1Layout);
        jFrameSelfDiag1Layout.setHorizontalGroup(
            jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameSelfDiag1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                        .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbunexplained)
                            .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbsorethroat)
                                    .addComponent(cbfeverorchills))
                                .addGap(107, 107, 107)
                                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmild)
                                    .addComponent(cblosstaste))))
                        .addGap(70, 70, 70)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbvomiting)
                    .addComponent(cbnewcough)
                    .addComponent(cbnonesymp))
                .addGap(40, 40, 40))
            .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(cbbseveresymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel4))
                    .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbcovidtested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnbacktoOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntoframe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jFrameSelfDiag1Layout.setVerticalGroup(
            jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSelfDiag1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbbcovidtested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbfeverorchills)
                    .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbmild)
                        .addComponent(cbnewcough)))
                .addGap(32, 32, 32)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbsorethroat)
                    .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cblosstaste)
                        .addComponent(cbvomiting)))
                .addGap(41, 41, 41)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbunexplained)
                    .addComponent(cbnonesymp))
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbbseveresymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jFrameSelfDiag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbacktoOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntoframe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jFrameSelfDiag2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameSelfDiag2.setSize(new java.awt.Dimension(750, 600));
        jFrameSelfDiag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFrameSelfDiag2MouseExited(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Do any of these apply to you?");
        jFrameSelfDiag2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 76, -1, -1));

        jCheckBox1.setText("Smoking or vaping");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jCheckBox2.setText("Pregnancy");
        jFrameSelfDiag2.getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jCheckBox3.setText("<html>Diabetes, high blood pressure,<br/> chronic kidney disease, or liver disease");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jCheckBox4.setText("<html>Chronic lung disease, such as moderate to severe asthma, <br/>COPD (chronic obstructive pulmonary disease),<br/> cystic fibrosis, or pulmonary fibrosis");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 50));

        jCheckBox5.setText("<html>Serious heart condition, such as heart failure, <br/>prior heart attack, or cardiomyopathy");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jCheckBox6.setText("<html>Weakened immune system from HIV,<br/> cancer treatement, use of medicines causing immune<br/> suppression, or other factors");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jCheckBox8.setText("<html>Stroke dementia, or other cerebrovascular<br/> disease or neurologic condition");
        jFrameSelfDiag2.getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jCheckBox9.setText("<html>Sickle cell disease, thalassemia,<br/> or other blood disorder");
        jFrameSelfDiag2.getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        cbcleanmedicalBG.setText("None of the above");
        jFrameSelfDiag2.getContentPane().add(cbcleanmedicalBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        btntoSelfDiag3.setText("Next");
        btntoSelfDiag3.setMaximumSize(new java.awt.Dimension(91, 23));
        btntoSelfDiag3.setMinimumSize(new java.awt.Dimension(91, 23));
        btntoSelfDiag3.setPreferredSize(new java.awt.Dimension(91, 23));
        btntoSelfDiag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoSelfDiag3ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(btntoSelfDiag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        btnbackSelfDiag1.setText("Previous");
        btnbackSelfDiag1.setMaximumSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag1.setMinimumSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag1.setPreferredSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackSelfDiag1ActionPerformed(evt);
            }
        });
        jFrameSelfDiag2.getContentPane().add(btnbackSelfDiag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jFrameSelfDiag3.setResizable(false);
        jFrameSelfDiag3.setSize(new java.awt.Dimension(750, 600));
        jFrameSelfDiag3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("In the last 14 days, did any of these apply to you?");
        jFrameSelfDiag3.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel7.setText("In the last 14 days, did you work or volunteer in a health care facility?");
        jFrameSelfDiag3.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your answer.", "I worked or volunteered in a heathcare facility in the last 14 days.", "I did not work or volunteer in a healthcare facility in the last 14 days.", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jFrameSelfDiag3.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Your answer.", "I cared for someone who has COVID-19.", "For at least 15 minutes, I was within 1.82 meters (6 feet) of someone who has COVID-19.", "I might have been exposed to COVID-19.", "I've had no known exposure to COVID-19." }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jFrameSelfDiag3.getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 20));

        btnSelfDiagResult.setText("Check result");
        btnSelfDiagResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfDiagResultActionPerformed(evt);
            }
        });
        jFrameSelfDiag3.getContentPane().add(btnSelfDiagResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        btnbackSelfDiag2.setText("Previous");
        btnbackSelfDiag2.setMaximumSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag2.setMinimumSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag2.setPreferredSize(new java.awt.Dimension(91, 23));
        btnbackSelfDiag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackSelfDiag2ActionPerformed(evt);
            }
        });
        jFrameSelfDiag3.getContentPane().add(btnbackSelfDiag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jFrameOption.setResizable(false);
        jFrameOption.setSize(new java.awt.Dimension(400, 400));
        jFrameOption.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameOptionWindowClosing(evt);
            }
        });

        jButton3.setText("Self-Diagnosis");
        jButton3.setMaximumSize(new java.awt.Dimension(230, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(230, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(230, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Area Statistics");
        jButton4.setMaximumSize(new java.awt.Dimension(230, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(230, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(230, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Area Regulations & Healthcare");
        jButton5.setMaximumSize(new java.awt.Dimension(230, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(230, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(230, 23));

        btnbacktomain.setText("Previous");
        btnbacktomain.setMaximumSize(new java.awt.Dimension(92, 23));
        btnbacktomain.setMinimumSize(new java.awt.Dimension(92, 23));
        btnbacktomain.setPreferredSize(new java.awt.Dimension(92, 23));
        btnbacktomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktomainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameOptionLayout = new javax.swing.GroupLayout(jFrameOption.getContentPane());
        jFrameOption.getContentPane().setLayout(jFrameOptionLayout);
        jFrameOptionLayout.setHorizontalGroup(
            jFrameOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameOptionLayout.createSequentialGroup()
                .addGroup(jFrameOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrameOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrameOptionLayout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(btnbacktomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrameOptionLayout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jFrameOptionLayout.setVerticalGroup(
            jFrameOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameOptionLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnbacktomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jFrameAreaStatistic.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jFrameAreaStatistic.setSize(new java.awt.Dimension(400, 400));
        jFrameAreaStatistic.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("What is your region ?");
        jLabel8.setMaximumSize(new java.awt.Dimension(112, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(112, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(112, 14));
        jFrameAreaStatistic.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 190, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("What is your Location ?");
        jLabel9.setMaximumSize(new java.awt.Dimension(112, 14));
        jFrameAreaStatistic.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        tfRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRegionActionPerformed(evt);
            }
        });
        tfRegion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRegionKeyTyped(evt);
            }
        });
        jFrameAreaStatistic.getContentPane().add(tfRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 30));

        tfLocation.setPreferredSize(null);
        tfLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocationActionPerformed(evt);
            }
        });
        tfLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLocationKeyTyped(evt);
            }
        });
        jFrameAreaStatistic.getContentPane().add(tfLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 30));

        btnAreaStatisticResult.setText("Check Result");
        btnAreaStatisticResult.setMaximumSize(new java.awt.Dimension(92, 23));
        btnAreaStatisticResult.setMinimumSize(new java.awt.Dimension(92, 23));
        btnAreaStatisticResult.setPreferredSize(new java.awt.Dimension(92, 23));
        btnAreaStatisticResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaStatisticResultActionPerformed(evt);
            }
        });
        jFrameAreaStatistic.getContentPane().add(btnAreaStatisticResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, -1));

        btnbacktoOption2.setText("Previous");
        btnbacktoOption2.setMaximumSize(new java.awt.Dimension(91, 23));
        btnbacktoOption2.setMinimumSize(new java.awt.Dimension(91, 23));
        btnbacktoOption2.setPreferredSize(new java.awt.Dimension(91, 23));
        btnbacktoOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktoOption2ActionPerformed(evt);
            }
        });
        jFrameAreaStatistic.getContentPane().add(btnbacktoOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        jFrameAreaStatistic.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "States", "Districts" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jFrameAreaStatistic.getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        login.setResizable(false);
        login.setSize(new java.awt.Dimension(500, 300));

        jPasswordField1.setText("jPasswordField1");

        jFormattedTextField1.setText("jFormattedTextField1");

        username.setText("username");

        password.setText("password");

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password)
                    .addComponent(username))
                .addGap(34, 34, 34)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogin)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(44, 44, 44)
                .addComponent(btnlogin)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tfAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAge.setText("Age");
        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });
        tfAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAgeKeyTyped(evt);
            }
        });

        tfCity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCity.setText("City");
        tfCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCityActionPerformed(evt);
            }
        });
        tfCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCityKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please provide information for analysis");

        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.setText("Name");
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNameKeyTyped(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.setActionCommand("self");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbbsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "abcxyz" }));
        cbbsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbsexActionPerformed(evt);
            }
        });

        jButton2.setText("I have account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCity)
                                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(tfAge))))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(cbbsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyTyped
        // TODO add your handling code here:
        
        char Name=evt.getKeyChar();
                if(!((Character.isAlphabetic(Name))||(Character.isSpaceChar(Name))))
                    evt.consume();
    }//GEN-LAST:event_tfNameKeyTyped

    private void tfAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAgeKeyTyped
        // TODO add your handling code here:
        
        limit1++;
        char Age=evt.getKeyChar() ;

        if (!(Character.isDigit(Age)))
            evt.consume();
        
    }//GEN-LAST:event_tfAgeKeyTyped

    private void tfCityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCityKeyTyped
        // TODO add your handling code here:
        char City=evt.getKeyChar();
         if(!((Character.isAlphabetic(City))||(Character.isSpaceChar(City))))
             evt.consume();
    }//GEN-LAST:event_tfCityKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // SUBMIT BUTTON
        Object selectedItem = cbbsex.getSelectedItem();
        JOptionPane.showMessageDialog(null,"Hello "+ tfName.getText()+"\nYour age is "+ tfAge.getText()+"\nYour city is "+tfCity.getText()+"\nYour Gender is "+selectedItem);
       jFrameOption.show();
       this.hide();
       jFrameOption.show();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbsexActionPerformed
     
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbsexActionPerformed

    private void cbbcovidtestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbcovidtestedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbcovidtestedActionPerformed

    private void btntoframe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoframe3ActionPerformed
        // TODO add your handling code here:
        if (cbnonesymp.isSelected())
            System.out.println("nothin");
        else
        {
            if (cbfeverorchills.isSelected())
                AddPoint.addPoint(1);
            if (cbmild.isSelected())
                AddPoint.addPoint(1);
            if (cbnewcough.isSelected())
                AddPoint.addPoint(1);
            if (cbsorethroat.isSelected())
                AddPoint.addPoint(1);
            if (cblosstaste.isSelected())
                AddPoint.addPoint(1);            
            if (cbvomiting.isSelected())
                AddPoint.addPoint(1);            
            if (cbunexplained.isSelected())
                AddPoint.addPoint(1);
        }
      jFrameSelfDiag1.hide();
      jFrameSelfDiag2.show();
     
      
    }//GEN-LAST:event_btntoframe3ActionPerformed

    private void cbbseveresymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbseveresymptomsActionPerformed

    }//GEN-LAST:event_cbbseveresymptomsActionPerformed

    private void cbsorethroatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsorethroatActionPerformed

    }//GEN-LAST:event_cbsorethroatActionPerformed

    private void cbfeverorchillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfeverorchillsActionPerformed

    }//GEN-LAST:event_cbfeverorchillsActionPerformed

    private void cblosstasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblosstasteActionPerformed

    }//GEN-LAST:event_cblosstasteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        login.show();
        

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
                if(true);
        JOptionPane.showMessageDialog(null,"login successful");
    }//GEN-LAST:event_btnloginActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void btntoSelfDiag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoSelfDiag3ActionPerformed
        if (cbcleanmedicalBG.isSelected())
            JOptionPane.showMessageDialog(null,"You have clean medical background");
        else
            JOptionPane.showMessageDialog(null,"You have medical background " );
        jFrameSelfDiag2.hide();
        jFrameSelfDiag3.show();
    }//GEN-LAST:event_btntoSelfDiag3ActionPerformed

    private void btnbackSelfDiag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackSelfDiag1ActionPerformed
        // TODO add your handling code here:
        jFrameSelfDiag1.show();
    }//GEN-LAST:event_btnbackSelfDiag1ActionPerformed

    private void btnbackSelfDiag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackSelfDiag2ActionPerformed
        // TODO add your handling code here:
        jFrameSelfDiag2.show();
        jFrameSelfDiag3.hide();
    }//GEN-LAST:event_btnbackSelfDiag2ActionPerformed

    private void btnSelfDiagResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfDiagResultActionPerformed
        // TODO add your handling code here:
        
        
        
        try(FileReader fileReader = new FileReader("filename.txt")) 
        {
            int ch = fileReader.read();
            String chString = "";
            while (ch!=-1)
            {
                chString = chString + (char)ch;
                ch = fileReader.read();
            }
            JOptionPane.showMessageDialog(null,"Your result is : " + chString + " point(s)");
        }
        catch (FileNotFoundException e) 
        {
            
        }
        catch (IOException e)
        {
            
        }
        jFrameSelfDiag3.dispose();
        jFrameOption.show();
        
        
    }//GEN-LAST:event_btnSelfDiagResultActionPerformed

    private void btnbacktoOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktoOption1ActionPerformed
        // TODO add your handling code here:
        jFrameOption.show();
        jFrameSelfDiag1.hide();
    }//GEN-LAST:event_btnbacktoOption1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jFrameSelfDiag1.show();
        jFrameOption.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnbacktomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktomainActionPerformed
        // TODO add your handling code here:
        jFrameOption.dispose();
        this.show();
        
    }//GEN-LAST:event_btnbacktomainActionPerformed

    private void jFrameSelfDiag1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameSelfDiag1WindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrameSelfDiag1WindowClosed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jFrameSelfDiag2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrameSelfDiag2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrameSelfDiag2MouseExited

    private void jFrameOptionWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameOptionWindowClosing
        // TODO add your handling code here:
        this.show();
    }//GEN-LAST:event_jFrameOptionWindowClosing

    private void tfLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLocationActionPerformed

    private void btnbacktoOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktoOption2ActionPerformed
        // TODO add your handling code here:
        jFrameOption.show();
    }//GEN-LAST:event_btnbacktoOption2ActionPerformed

    private void btnAreaStatisticResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaStatisticResultActionPerformed
        // TODO add your handling code here:
        //Data newData = new Data();
        String msg = (String)jComboBox4.getSelectedItem();
        switch (msg)
        {
            case "General":
                JOptionPane.showMessageDialog(null, newData.displayGeneralStats());
                break;
            case "States":
                String msg2 = (String)jComboBox2.getSelectedItem();
                JOptionPane.showMessageDialog(null, newData.displayStatesStats(msg2));
                break;
            case "Districts":
                String msg3 = (String)jComboBox2.getSelectedItem();
                JOptionPane.showMessageDialog(null, newData.displayStatesStats(msg3));
                break;
        }
                
        /*JOptionPane.showMessageDialog(null,"Your Location is "+ tfLocation.getText()+"\nYour Region is "+ tfRegion.getText());
        if (tfRegion.getText().equals("World"))
        {
            try 
            {
                JOptionPane.showMessageDialog(null, newData.displayGeneralStats());
            } 
            catch (Exception exception) 
            {
            exception.printStackTrace();
            }
        }
        if (tfRegion.getText().equals("States"))
        {
            try 
            {
                JOptionPane.showMessageDialog(null, newData.displayStatesStats(tfLocation.getText()));
            } 
            catch (Exception exception) 
            {
            exception.printStackTrace();
            }
        }
        if (tfRegion.getText().equals("Districts"))
        {
            try 
            {
                JOptionPane.showMessageDialog(null, newData.displayDistrictsStats(tfLocation.getText()));
            } 
            catch (Exception exception) 
            {
            exception.printStackTrace();
            }
        }*/
    }//GEN-LAST:event_btnAreaStatisticResultActionPerformed

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void tfRegionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRegionKeyTyped
        // TODO add your handling code here:
        limit1++;
       char tfRegion=evt.getKeyChar();
         if(!(Character.isAlphabetic(tfRegion))||(Character.isSpaceChar(tfRegion)))
             evt.consume();
        
        
    }//GEN-LAST:event_tfRegionKeyTyped

    private void tfLocationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLocationKeyTyped
        // TODO add your handling code here:
        limit1++;
        char tfLocation=evt.getKeyChar() ;

        if (!(Character.isAlphabetic(tfLocation))||(Character.isSpaceChar(tfLocation)))
            evt.consume();
    }//GEN-LAST:event_tfLocationKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jFrameAreaStatistic.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRegionActionPerformed

    private void tfCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCityActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        String msg = (String)jComboBox4.getSelectedItem();
        switch (msg)
        {
            case "States":
                Object[] a = newData.getNames("states");
                Arrays.sort(a);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(a));
                break;
            case "Districts":
                Object[] b = newData.getNames("districts");
                Arrays.sort(b);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(b));
                break;
            default: jComboBox2.removeAllItems();
                
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        char City;
        char Age;
        char Name;
        char sex;
        char tfLocation;
        char tfRegion;
        CreateFile.newFile();
        try (FileWriter fileWriter = new FileWriter("filename.txt"))
        {
            String filecontent = "0";
            fileWriter.write(filecontent);
            fileWriter.close();
        }    
        catch (IOException e){}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaStatisticResult;
    private javax.swing.JButton btnSelfDiagResult;
    private javax.swing.JButton btnbackSelfDiag1;
    private javax.swing.JButton btnbackSelfDiag2;
    private javax.swing.JButton btnbacktoOption1;
    private javax.swing.JButton btnbacktoOption2;
    private javax.swing.JButton btnbacktomain;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btntoSelfDiag3;
    private javax.swing.JButton btntoframe3;
    private javax.swing.JComboBox<String> cbbcovidtested;
    private javax.swing.JComboBox<String> cbbseveresymptoms;
    private javax.swing.JComboBox<String> cbbsex;
    private javax.swing.JCheckBox cbcleanmedicalBG;
    private javax.swing.JCheckBox cbfeverorchills;
    private javax.swing.JCheckBox cblosstaste;
    private javax.swing.JCheckBox cbmild;
    private javax.swing.JCheckBox cbnewcough;
    private javax.swing.JCheckBox cbnonesymp;
    private javax.swing.JCheckBox cbsorethroat;
    private javax.swing.JCheckBox cbunexplained;
    private javax.swing.JCheckBox cbvomiting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFrame jFrameAreaStatistic;
    private javax.swing.JFrame jFrameOption;
    private javax.swing.JFrame jFrameSelfDiag1;
    private javax.swing.JFrame jFrameSelfDiag2;
    private javax.swing.JFrame jFrameSelfDiag3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JFrame login;
    private javax.swing.JLabel password;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfLocation;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRegion;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
int limit1=0;


}
